# Import 

In [100]:
import numpy as np

# The Basics

In [101]:
a = np.array([1,2,3]) ### Initialization
a

array([1, 2, 3])

In [102]:
b = np.array([[0.0 , 9.0 , 7.0],[6.0,5.0,4.0]])
b

array([[0., 9., 7.],
       [6., 5., 4.]])

### how to get dimensions ?

In [103]:
### Get Dimensions
a.ndim

1

In [104]:
b.ndim

2

### Another imp thing is shape

In [105]:
a.shape

(3,)

In [106]:
b.shape

(2, 3)

### Get type 

In [107]:
a.dtype

dtype('int64')

### Lets say if we didnt want int 64  data type and instead wanted int 16

In [108]:
a = np.array([1,2,3] , dtype = 'int16')
a.dtype

dtype('int16')

### get Size (many ways)

In [109]:
a.itemsize
### if int 32 
a = np.array([1,2,3] , dtype = 'int32')
a.itemsize

4

### Get len of array

In [110]:
a.size

3

### Get total size of how many bytes does entire array aquire



In [111]:
a.size*a.itemsize

12

#### Or we can do this


In [112]:
a.nbytes

12

# Accessing/Changing Specific elements , rows , columns , etc

In [113]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [114]:
# Get Specific Elemeent [r,c]
print(a[1 ,5]) # to get 13
print(a[1,-2])

13
13


In [115]:
# Get specfic Row
print(a[1,:])

[ 8  9 10 11 12 13 14]


In [116]:
# Get specific Col
print(a[:,1])

[2 9]


In [117]:
# getting a little more fance [startindex : endindex : stepsize]
print(a[0,1::2])

[2 4 6]


In [118]:
# Change the value
print(a)
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [119]:
print(a)
a[:,2] = 5
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


3-d Example

In [120]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [121]:
# to get element work outside in

print(b[0,1,1])

4


In [122]:
print(b[:,1,:])
b[:,1,:] = [[9,9],[9,9]]


[[3 4]
 [7 8]]


In [123]:
print(b[:,1,:])

[[9 9]
 [9 9]]


# Initializing diff types of array

all zeros first

In [124]:
# All zeros
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [125]:
# all 1
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

We can even specify the data type in this

In [126]:
np.ones((2,3),dtype='int8')

array([[1, 1, 1],
       [1, 1, 1]], dtype=int8)

#### Lets say we dont want to do 1 and 0 only but some other number

In [127]:
np.full((2,2),99,dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [132]:
# Any other number (full_like)
np.full_like(a , 4)


array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [134]:
# orrrr
np.full(a.shape,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

Init a array of random numbers

In [138]:
np.random.rand(4,2,3) #instead of passing a tuple like before we can pass the integer pair directly

array([[[0.5718745 , 0.88817644, 0.84928356],
        [0.68726784, 0.63344928, 0.42383159]],

       [[0.82717162, 0.47294664, 0.69969327],
        [0.56076029, 0.49737515, 0.0817132 ]],

       [[0.82389536, 0.92080956, 0.69992838],
        [0.37391276, 0.51192529, 0.69632013]],

       [[0.25361206, 0.2692713 , 0.09666944],
        [0.2286638 , 0.60244454, 0.18230932]]])

In [142]:
np.random.random_sample(a.shape) # uses other array as blueprint

array([[0.5768644 , 0.44756847, 0.88576185, 0.22788932, 0.99232318,
        0.005354  , 0.78430951],
       [0.5138178 , 0.98058193, 0.92132473, 0.2585255 , 0.12757749,
        0.06512307, 0.50954844]])

In [149]:
# random int

np.random.randint(7,10,size=(3,3)) # gets random int between 7 and 10 
# exclisive of 10 (upper limit)

array([[7, 9, 8],
       [8, 8, 8],
       [7, 7, 8]], dtype=int32)

In [150]:
# identity matrix

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Repeating an array

In [152]:
arr = np.array([1,2,3]) # 1d array
r1 = np.repeat(arr,3)
r1

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [157]:
arr = np.array([[1,2,3]]) # 2d array
r1 = np.repeat(arr,3,axis = 0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [162]:
test = np.ones((5,5))
test[1:4 , 1:4] = np.zeros((3,3))
test[2:3,2:3] = np.full((1,1),9)
test

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

### Be carefull when copying arrays!!!

In [164]:
a = np.array([1,2,3])
b= a
b[0] = 100
a

array([100,   2,   3])

its because b is referencing to a not assigning copy of a

In [166]:
a = np.array([1,2,3])
b= a.copy()
b[0] = 100
a

array([1, 2, 3])

# Mathematics

In [171]:
a = np.array(range(1,5))
a 


array([1, 2, 3, 4])

In [172]:
a+2

array([3, 4, 5, 6])

In [173]:
a-2

array([-1,  0,  1,  2])

In [174]:
a*2

array([2, 4, 6, 8])

In [175]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [176]:
a+=2
a

array([3, 4, 5, 6])

In [177]:
b = np.array([1,0,1,0])
a+b

array([4, 4, 6, 6])

In [178]:
a**2

array([ 9, 16, 25, 36])

In [179]:
np.sin(a)

array([ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ])

# Linear Algebra

In [181]:
a= np.ones((2,3))
print(a)

b= np.full((3,2),2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [183]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [184]:
# find the determinant

c=np.identity(3)

np.linalg.det(c)

np.float64(1.0)

We can also find eigen values or inverse or trace or norms or decompositon etc..... of matrix and all sorts of things


# Statistics

In [186]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [187]:
np.min(stats)

np.int64(1)

In [188]:
np.max(stats)

np.int64(6)

In [191]:
# lets say min of all the rows

np.min(stats,axis = 1)

array([1, 4])

In [192]:
# min of all the columns

np.min(stats , axis = 0)

array([1, 2, 3])

In [194]:
np.sum(stats)

np.int64(21)

In [196]:
np.sum(stats , axis = 0) ## all sum cols

array([5, 7, 9])

# Reorganizing Arrays

In [202]:
before = np.array([list(range(1,5)),list(range(5,9))]) 
before

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [203]:
before.shape

(2, 4)

Lets say we wanted it to make 8x1

In [206]:
after = before.reshape((8,1))
after

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [207]:
after = before.reshape((2,2,2))
after

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

As long as the before and after have the same amount of values we can reshape in whatever way we want

#### Vertical Stacking matrices

In [211]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [212]:
np.vstack([v1,v2,v2,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [215]:
h1 = np.zeros((2,3))
h2 = np.ones((2,3))

np.hstack([h1,h2])

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

# Miscellaneous

In [ ]:
filedata = np.genfromtxt('data.txt', delimiter=',')
print(filedata)
filedata = filedata.astype('int32') ## by default it was flaot we chaneged to int
filedata


[[ 1.  2.  3.  4.  5.]
 [10. 11. 12. 13. 14.]]


array([[ 1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14]], dtype=int32)

#### Boolean Masking and adv indexing

In [223]:
filedata > 5

array([[False, False, False, False, False],
       [ True,  True,  True,  True,  True]])

In [225]:
filedata[filedata > 5] # Only grabs value > 5

array([10, 11, 12, 13, 14], dtype=int32)

Also one cool thing is we can index with a list in numpy

In [228]:
a = np.array(range(1,10))
a[[1,5,7]] # passed in a list

array([2, 6, 8])

In [235]:
np.any(filedata > 13 ,axis = 0) # checking in each col if any value is greater than 13

array([False, False, False, False,  True])

In [236]:
np.all(filedata>4,axis = 0)

array([False, False, False, False,  True])

In [255]:
(filedata > 5) & (filedata < 12)

array([[False, False, False, False, False],
       [ True,  True, False, False, False]])

In [262]:
arr = np.array(range(1,31))
arr = arr.reshape((6,5))
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [264]:
arr[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [265]:
arr[[0,4,5],3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])

## Yeah thats it for the basics!!!!!!!!!!!